export const MAGPI_ACP_TREE_COMMAND = '__magpi_acp_internal_tree'
export const MAGPI_ACP_MARK_CLIENT_MESSAGE_COMMAND = '__magpi_acp_internal_mark_client_message'
export const MAGPI_ACP_REWIND_CLIENT_MESSAGE_COMMAND = '__magpi_acp_internal_rewind_client_message'
export const MAGPI_ACP_TREE_SELECTION_TITLE = 'Choose where Pi should continue from'
export const MAGPI_ACP_TREE_SUMMARY_TITLE = 'Summarize the branch being left?'
export const MAGPI_ACP_TREE_REWIND_METHOD = '_magpi-acp/session/rewind'
export const MAGPI_ACP_TREE_REWIND_CAPABILITY = 'magpi-acp/tree-rewind'
export const MAGPI_ACP_CLIENT_MESSAGE_ID_META = 'magpi-acp/client-message-id'
