name: Publish Package

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write # Required for OIDC
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '24.x'
          registry-url: 'https://registry.npmjs.org'

      - run: npm install -g npm@latest

      - run: npm ci
      - run: npm run check
      - name: Publish and tag
        run: |
          TAG="v$(node -p "require('./package.json').version")"
          git fetch --tags
          git tag "$TAG"
          npm publish --access public --provenance
          git push origin "$TAG"
